site_name: Silas Maths

repo_name: Silas Maths
repo_url: https://github.com/silaspe/maths

nav:
  - Home: README.md
  - Calculus: derivatives.md
  - Polynomial: polynomial.md
  - Calculus part 2: calculus_2.md
  - Complex: complex.md
  - Jacobian: jacobian.md
  - Gamma: gamma.md
  - Hyperbolic: hyperbolic.md
  - Harmonic: harmonic.md
  - Trigonometry: trigonometry.md
  - Eigenstuff: eigen.md
  - Quadratic (again): quadratic.md
  - Binomial: binomial.md
  - fractional calculas: fractional_calculas.md
  - fibbonacci: fibonacci_calculas.md

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


use_directory_urls: false

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.extra
  - markdown.extensions.codehilite
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

