site_name: Silas Maths

repo_name: Silas Maths
repo_url: https://github.com/silaspe/maths

nav:
  - Home: README.md
  - Brainstorming a new page: brainstorm.md
  - Calculus: derivatives.md
  - Polynomial: polynomial.md
  - Calculus part 2: calculus_2.md
  - Trigonometry: trigonometry.md
  - Complex: complex.md
  - Jacobian: jacobian.md
  - Eigenstuff: eigen.md
  - Gamma: gamma.md
  - Harmonic: harmonic.md
  - Binomial: binomial.md
  - Fractional calculus: fractional_calculas.md
  - Fibbonacci: fibbonacci.md
  - Probability: probability.md
  - Complex II: complex_2.md
  - The strand puzzle: the_strand_puzzle.md
  - The infamous "arctan puzzle": arctan.md
  - Modular arithmetic: mod.md
  - Geometric algebra: geometric_algebra.md
  - Set theory: set_theory.md
  - NOOOOOOOOOO: streak.md
  - Code repo: actual_repo.md
  - The best way to count: binary.md
  - Geometric algebra 2: geometric_algebra_2.md
  - Lambda calculus: lambda.md
  - Random thoughts: rand.md
  - Summer of Math Exposition 4: some4.md
  - Set theory II: logic.md
  - Projective geometry: projective_geometry.md
  - Lambda Calculus revisited: lcr.md
  - Linear algebra: linear.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


use_directory_urls: false

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.extra
  - markdown.extensions.codehilite
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

