site_name: Silas Maths

repo_name: Silas Maths
repo_url: https://github.com/silaspe/maths

nav:
  - Home: README.md
  - Brainstorming a new page: aa.md
  - Calculus: derivatives.md
  - Polynomial: polynomial.md
  - Calculus part 2: calculus_2.md
  - Trigonometry: trigonometry.md
  - Complex: complex.md
  - Jacobian: jacobian.md
  - Eigenstuff: eigen.md
  - Gamma: gamma.md
  - Harmonic: harmonic.md
  - Binomial: binomial.md
  - Fractional calculus: fractional_calculas.md
  - Fibbonacci: fibbonacci.md
  - Probability: probability.md
  - Complex II: complex_2.md
  - The strand puzzle: the_strand_puzzle.md
  - The infamous "arctan puzzle": arctan.md
  - Modular arithmetic: mod.md
  - Geometric algebra: geomatric_algebra.md
  - Set theory: set_theory.md

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


use_directory_urls: false

plugins:
  - search
  - with-pdf
  # - with-pdf:
  #     render_js: true

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.extra
  - markdown.extensions.codehilite
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

